name: Lab 3 Create Artifact

# trigger
on:
  push:
    branches:
    - main
    pull_request:
      branches:
    - main

# job
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

# checkout our repo
    - uses: actions/checkout@v3

# use node
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: "18"

# pretend build
    - name: Pretend to build
      run: echo Pretending to build some kind of app...

# upload our file
    - name: Push artifact foo.txt
      uses: actions/upload-artifact@v3
      with:
      name: my-artifact
      path: hello.txt
